<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Database\Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logic\WebAppMTGLogic.csproj" />
  </ItemGroup>

</Project>
